### ISSUE TITLE
Allow for mixed types lists like (string|number)[]

### ISSUE THREAD

**Issue by ExtReMLapin** [IntrinsicLabsAI/gbnfgen#25]
Title

Could it be possible to support lists with multiple types ?

Thanks.

**Comment by a10y** [comment]
Hey @ExtReMLapin , checkout version 0.11.0 which includes #28 that I believe should suit your use-case. Let us know if that doesn't work for you!

**Comment by ExtReMLapin** [comment]
Thanks !
giga based
