### ISSUE TITLE
Request: support for Python classes and/or `dataclass`

### ISSUE THREAD

**Issue by jamesbraza** [IntrinsicLabsAI/gbnfgen#7]
It seems like TypeScript and Python are two of the main languages for the LLM community.

It would be cool to support Python with this tool:
- Native classes
- [`dataclasses.dataclass`](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass)

**Comment by a10y** [comment]
Hey @jamesbraza , thanks for filing! This repo is solely based on TypeScript, using the TypeScript compiler under the hood to actually parse and generate grammars. You can check this out in the `compileSync` function in the code here https://github.com/IntrinsicLabsAI/gbnfgen/blob/main/src/compiler.ts#L194

Given the tech stack we're using, support for Python types is out of scope but agree that there does deserve to be a Python library in a similar vein to this one.

**Comment by a10y** [comment]
One thing to note: llama.cpp repo contains a Python script to convert a JSON Schema to a grammar https://github.com/ggerganov/llama.cpp/blob/master/examples/json-schema-to-grammar.py

In Python, if you're using Pydantic, you can build a class and [extract it's JSON Schema](https://docs.pydantic.dev/latest/concepts/json_schema/) like so:

```python
from pydantic import BaseModel
import json

class CarType(BaseModel):
  make: str
  model: str
  year: number

with open("car-schema.json", "w") as f:
  f.write(json.dumps(CarType.model_json_schema()))
```

Note that I have not tested this but from my understanding of the pieces that's one way you could do something similar with Python

**Comment by jamesbraza** [comment]
Okay gotchu, sounds good on this being out of the scope of this repo.

And it's a great idea to go from `pydantic` --> JSON schema --> grammar.  Thank you, appreciate the pointer!
